using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ObjectLibrary
{
    public class SalesAndOrdersObject
    {
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by a tool.
        //     Runtime Version:4.0.30319.42000
        //
        //     Changes to this file may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------
        public int Order_Id { get; set; }
        public int Production_Id { get; set; }
        public string Price_Code { get; set; }
        public int Customer_Id { get; set; }
        public long Order_Qty { get; set; }
        public long Order_Slip_Number { get; set; }
        public string Order_Status { get; set; }
        public DateTime Entry_Date { get; set; }
        public string Order_Remarks { get; set; }
        public Double Sales_Amount { get; set; }
        public string Search { get; set; }


    }
}
