using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ObjectLibrary
{
    public class UserObject
    {
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by a tool.
        //     Runtime Version:4.0.30319.42000
        //
        //     Changes to this file may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------
        public int Role_Id { get; set; }
        public string UserName{ get; set; }
        public string Password{ get; set; }
        public string Status { get; set; }
        public string ImagePath { get; set; }
        public string User_Search { get; set; }
    }
}
